# patcurryworks.com/.travis.yml
language:
  - python

python:
  - "3.6"

install:
  - "pip install -r requirements.txt"

script:
  - "echo 'hey!'"
  - "python manage.py test --settings=main.settings.dev"
