# Generated by Django 2.0.4 on 2018-04-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('amount', models.IntegerField(default=1)),
                ('sets', models.IntegerField(default=1)),
                ('units', models.CharField(choices=[('sec', 'seconds'), ('reps', 'repetitions')], default='reps', max_length=4)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
