# Generated by Django 2.0.4 on 2018-04-10 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='sets',
        ),
        migrations.AddField(
            model_name='session',
            name='exercises',
            field=models.ManyToManyField(through='workouts.Set', to='workouts.Exercise'),
        ),
        migrations.AddField(
            model_name='set',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.Session'),
        ),
        migrations.AlterField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.Exercise'),
        ),
    ]
