# Generated by Django 2.0.4 on 2018-04-11 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20180410_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='exercises',
            field=models.ManyToManyField(related_name='sessions', through='workouts.Set', to='workouts.Exercise'),
        ),
        migrations.AlterField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.Exercise'),
        ),
        migrations.AlterField(
            model_name='set',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.Session'),
        ),
    ]
