# Generated by Django 2.0.4 on 2018-04-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_session_session_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
